- Added options to rsync aweworker space and restart remote hosts - Added max_client_failure option to awe - Merged Keiths aweworker fixes to handle multiple client groups better

diff --git a/config/postprocess_aweworker b/config/postprocess_aweworker
--- a/config/postprocess_aweworker
+++ b/config/postprocess_aweworker
@@ -19,12 +19,12 @@ $base_url=~s/\///;
 
 my @sl=myservices();
 my $service=$sl[0];
-my $base_dir=$cfg->{services}->{$service}->{'baseworkdir'};
 
 print "Service: $service\n";
 
 # Fix up config
 my $file=$KB_DEPLOY."/services/awe_service/conf/awec.cfg";
+my $baseworkdir=$cfg->{'services'}->{$service}->{'baseworkdir'};
 my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];
 
 $mcfg->newval('Client','group','replace') or die "Unable to set group";
@@ -33,36 +33,47 @@ $mcfg->newval('Client','clientgroup_token',"replace");
 $mcfg->newval('Client','serverurl',$cfg->{services}->{$service}->{'serverurl'}) or die "Unable to set serverurl";
 $mcfg->setval('Client','supported_apps','*');
 $mcfg->setval('Client','name','hostname');
-$mcfg->setval('Client','workpath',$base_dir."/work");
-$mcfg->setval('Directories','data',$base_dir."/data");
-$mcfg->setval('Directories','logs',$base_dir."/logs");
+# added kkeller 30jul2015.  not generally suitable for production
+$mcfg->setval('Client','auto_clean_dir','false');
 
 
-my $sdir=$KB_DEPLOY."/services/awe_service/";
-
-mysystem("cp $KB_DEPLOY/services/awe_service/start_{aweclient,service}");
-mysystem("cp $KB_DEPLOY/services/awe_service/stop_{aweclient,service}");
-
-
-my $defaultdone=0;
+my @aweGroups;
 foreach my $token (split /,/,$cfg->{services}->{$service}->{'tokens'}){
   my @l=split /[=|]/,$token;
   my $group=$l[1];
+  push @aweGroups,$group;
   $mcfg->setval('Client','group',$group);
   $mcfg->setval('Client','clientgroup_token',$token);
-
+  $mcfg->setval('Client','workpath',$baseworkdir . '/' . $group . '/work');
+  $mcfg->setval('Directories','data',$baseworkdir . '/' . $group . '/data');
+  $mcfg->setval('Directories','logs',$baseworkdir . '/' . $group . '/logs');
   my $out=$file;
-  if ($defaultdone == 1){
-    $mcfg->setval('Client','workpath',$base_dir."/work.".$group);
-    $mcfg->setval('Directories','data',$base_dir."/data.".$group);
-    $mcfg->setval('Directories','logs',$base_dir."/logs.".$group);
-    $out=~s/cfg$//;
-    $out.="$group.cfg";
-    update_scripts($sdir,$group);
-  }
+  $out=~s/cfg$//;
+  $out.="$group.cfg";
   print "Updating $out\n";
   $mcfg->WriteConfig($out) or die "Unable to write $file";
-  $defaultdone=1;
+}
+
+foreach my $action ('start','stop')
+{
+  my $script=<<EOF;
+#!/bin/bash
+for worker in @aweGroups
+do
+    $KB_DEPLOY/services/awe_service/${action}_aweclient \$worker
+done
+EOF
+
+  my $scriptfile="$KB_DEPLOY/services/awe_service/${action}_service";
+  open (SCRIPT, '>', $scriptfile) or die "couldn't open $scriptfile: $!";
+  print SCRIPT $script;
+  close SCRIPT;
+
+  # need to protect / in $baseworkdir.  yay leaning toothpick syndrome!
+  $baseworkdir=~s/\//\\\//g;
+  # kkeller: i use perl as my sed
+  mysystem("perl -pi -e 's|^PID_FILE=.*|PID_FILE=$baseworkdir/client\\\$suffix.pid|;' $KB_DEPLOY/services/awe_service/${action}_aweclient");
+  mysystem("perl -pi -e 's|^AWE_DIR=.*|AWE_DIR=$baseworkdir|;' $KB_DEPLOY/services/awe_service/${action}_aweclient");
 }
 
 # May not be needed anymore.  Check.
@@ -81,6 +92,22 @@ if ( ! -e "$KB_DEPLOY/bin/assemble_contigset_from_reads") {
   mysystem("sed  -i 's/\\..fasta_to_contigset/fasta_to_contigset/' $KB_DEPLOY/bin/assemble_contigset_from_reads");
 }
 
+# Sync and restart other aweworkers
+if (defined $cfg->{services}->{$service}->{shareddir}){
+  my $shared=$cfg->{services}->{$service}->{shareddir};
+  my @s=stat $KB_DEPLOY;
+  my $ts=$s[10];
+
+  mysystem("rsync -avvz --exclude *.log --exclude *.pid $KB_DEPLOY/ $shared/deployment.$ts");
+  if (defined $cfg->{services}->{$service}->{aweworkers}){
+    for my $host (split /,/, $cfg->{services}->{$service}->{aweworkers}) {
+      mysystem("ssh $host $KB_DEPLOY/services/awe_service/stop_service || echo Ignore");
+      mysystem("ssh $host \"rm $KB_DEPLOY;ln -s $shared/deployment.$ts $KB_DEPLOY\"");
+      mysystem("ssh $host $KB_DEPLOY/services/awe_service/start_service || echo Ignore");
+    }
+  }
+}
+
 # TODO
 #
 # export TOKEN=$(grep token ~/.kbase_config|sed 's/token=//')
@@ -89,27 +116,3 @@ if ( ! -e "$KB_DEPLOY/bin/assemble_contigset_from_reads") {
 #
 # Grab output and stuff in config
 
-sub update_scripts {
-  my $sdir=shift;
-  my $group=shift;
-
-  # TODO: This is a hack
-  open(START,">> $sdir/start_service") or die "Unable to modify start script";
-  print START "AWEC_CONFIG=/kb/deployment/services/awe_service/conf/awec.$group.cfg\n";
-  print START "PID_FILE=/kb/deployment/services/awe_service/client$group.pid\n";
-  print START "\$KB_RUNTIME/sbin/daemonize -v -o \$AWE_DIR/awec-start$group.log -e \$AWE_DIR/awec-start$group.log -p \$PID_FILE \\\n";
-  print START "      \$KB_TOP/bin/awe-client -conf \$AWEC_CONFIG\n";
-  close START;
-
-  open(STOP,">> $sdir/stop_service");
-  print STOP "PID_FILE=/kb/deployment/services/awe_service/client$group.pid\n";
-  print STOP "if [ -f \$PID_FILE ]; then\n";
-  print STOP "    PID=`cat \$PID_FILE`\n";
-  print STOP "    echo \"terminating process ID \$PID\"\n";
-  print STOP "    kill -TERM -\$PID\n";
-  print STOP "    rm \$PID_FILE\n";
-  print STOP "else\n";
-  print STOP "    echo \"No pid file \$PID_FILE found for awe client\"\n";
-  print STOP "fi\n";
-  close STOP;
-}
